# ============================================================
# MOVIE BOX OFFICE PREDICTOR — Streamlit App
# ============================================================
# Install: pip install streamlit
# Run:     streamlit run movie_app.py
# Needs:   xgb_model.pkl, scaler.pkl, features.pkl
#          (generated by movie_model.py)
# ============================================================

import streamlit as st
import joblib
import numpy as np
import pandas as pd

# ── Page config ───────────────────────────────────────────────
st.set_page_config(
    page_title="Movie Box Office Predictor",
    page_icon="🎬",
    layout="centered",
)

# ── Custom CSS ────────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Inter:wght@300;400;600&display=swap');

html, body, [class*="css"] {
    font-family: 'Inter', sans-serif;
    background-color: #0d0d0d;
    color: #eeeeee;
}

.main { background-color: #0d0d0d; }

h1, h2, h3 {
    font-family: 'Space Mono', monospace !important;
    color: #e6b800 !important;
}

.stButton > button {
    background-color: #e6b800;
    color: #0d0d0d;
    font-family: 'Space Mono', monospace;
    font-weight: 700;
    font-size: 16px;
    border: none;
    border-radius: 6px;
    padding: 0.6rem 2rem;
    width: 100%;
    transition: all 0.2s;
}
.stButton > button:hover {
    background-color: #ffcd00;
    transform: translateY(-1px);
}

.stSelectbox > div, .stSlider > div {
    background-color: #141414;
}

div[data-testid="stMetricValue"] {
    font-family: 'Space Mono', monospace;
    font-size: 2.4rem !important;
    color: #e6b800 !important;
}

.result-box {
    border-radius: 12px;
    padding: 2rem;
    text-align: center;
    margin: 1.5rem 0;
}
.hit-box {
    background: linear-gradient(135deg, #1a1a00, #2a2200);
    border: 2px solid #e6b800;
}
.flop-box {
    background: linear-gradient(135deg, #1a0000, #2a0a0a);
    border: 2px solid #cc3333;
}
.result-label {
    font-family: 'Space Mono', monospace;
    font-size: 3rem;
    font-weight: 700;
    letter-spacing: 4px;
    margin: 0;
}
.hit-label  { color: #e6b800; }
.flop-label { color: #cc3333; }
.confidence {
    font-size: 1rem;
    color: #aaaaaa;
    margin-top: 0.5rem;
    font-family: 'Inter', sans-serif;
}
.insight-card {
    background-color: #141414;
    border-left: 3px solid #e6b800;
    border-radius: 4px;
    padding: 0.8rem 1rem;
    margin: 0.5rem 0;
    font-size: 0.9rem;
    color: #cccccc;
}
.section-title {
    font-family: 'Space Mono', monospace;
    color: #e6b800;
    font-size: 0.75rem;
    letter-spacing: 3px;
    text-transform: uppercase;
    margin: 1.5rem 0 0.75rem;
    border-bottom: 1px solid #222;
    padding-bottom: 0.4rem;
}
</style>
""", unsafe_allow_html=True)

# ── Load model artifacts ──────────────────────────────────────
@st.cache_resource
def load_artifacts():
    model    = joblib.load("xgb_model.pkl")
    scaler   = joblib.load("scaler.pkl")
    features = joblib.load("features.pkl")
    return model, scaler, features

model, scaler, FEATURES = load_artifacts()

# ── Director database (hit rates from training data) ─────────
DIRECTOR_TIERS = {
    "Proven hitmaker (>70% hit rate)":   0.80,
    "Reliable director (50–70%)":        0.60,
    "Mixed track record (30–50%)":       0.40,
    "Mostly flops or new director (<30%)": 0.20,
}

# ── Header ────────────────────────────────────────────────────
st.markdown("# 🎬 MOVIE BOX OFFICE PREDICTOR")
st.markdown("*Will it be a hit or a flop? Enter pre-release details below.*")
st.markdown("---")

# ── Input form ────────────────────────────────────────────────
st.markdown('<p class="section-title">🎥 Production Details</p>', unsafe_allow_html=True)

col1, col2 = st.columns(2)

with col1:
    budget_m = st.slider(
        "Production budget ($M)", 
        min_value=1, max_value=400, value=50, step=1,
        help="Budget in millions USD"
    )
    runtime = st.slider(
        "Runtime (minutes)", 
        min_value=60, max_value=210, value=110, step=1
    )
    popularity = st.slider(
        "Pre-release buzz (TMDB popularity score)",
        min_value=1, max_value=200, value=30, step=1,
        help="Higher = more social media / press attention pre-release"
    )

with col2:
    primary_genre = st.selectbox(
        "Primary genre",
        ["Action", "Adventure", "Animation", "Comedy", "Drama",
         "Horror", "Romance", "Thriller", "Other"]
    )
    director_tier = st.selectbox(
        "Director track record",
        list(DIRECTOR_TIERS.keys())
    )
    studio_type = st.selectbox(
        "Studio",
        ["Major studio (Warner, Universal, Disney, etc.)",
         "Independent / smaller studio"]
    )

st.markdown('<p class="section-title">📅 Release Strategy</p>', unsafe_allow_html=True)

col3, col4 = st.columns(2)
with col3:
    season = st.selectbox(
        "Release season",
        ["Summer (Jun–Aug)", "Holiday (Nov–Dec)",
         "Spring (Mar–May)", "Off-peak (Jan–Feb, Sep–Oct)"]
    )
with col4:
    is_franchise = st.selectbox(
        "Franchise / sequel?",
        ["Yes — part of a franchise or sequel", "No — original film"]
    )

st.markdown("---")

# ── Predict button ────────────────────────────────────────────
if st.button("🎬  PREDICT"):

    # Build feature vector
    log_budget     = np.log10(budget_m * 1_000_000)
    popularity_log = np.log1p(popularity)
    dir_hit_rate   = DIRECTOR_TIERS[director_tier]
    big_studio     = 1 if "Major" in studio_type else 0
    franchise_flag = 1 if "Yes" in is_franchise else 0

    genre_map = {g: 0 for g in
                 ["Action","Adventure","Animation","Comedy",
                  "Drama","Horror","Romance","Thriller"]}
    if primary_genre in genre_map:
        genre_map[primary_genre] = 1

    season_map = {"summer": 0, "holiday": 0, "spring": 0}
    if "Summer"  in season: season_map["summer"]  = 1
    if "Holiday" in season: season_map["holiday"] = 1
    if "Spring"  in season: season_map["spring"]  = 1

    feature_vector = {
        "log_budget":        log_budget,
        "runtime":           runtime,
        "popularity_log":    popularity_log,
        "director_hit_rate": dir_hit_rate,
        "is_franchise":      franchise_flag,
        "big_studio":        big_studio,
        "genre_Action":      genre_map["Action"],
        "genre_Comedy":      genre_map["Comedy"],
        "genre_Drama":       genre_map["Drama"],
        "genre_Thriller":    genre_map["Thriller"],
        "genre_Adventure":   genre_map["Adventure"],
        "genre_Horror":      genre_map["Horror"],
        "genre_Romance":     genre_map["Romance"],
        "genre_Animation":   genre_map["Animation"],
        "season_summer":     season_map["summer"],
        "season_holiday":    season_map["holiday"],
        "season_spring":     season_map["spring"],
    }

    X_input = pd.DataFrame([feature_vector])[FEATURES]
    proba   = model.predict_proba(X_input)[0][1]
    pred    = int(proba >= 0.5)

    # ── Result display ────────────────────────────────────────
    if pred == 1:
        st.markdown(f"""
        <div class="result-box hit-box">
            <p class="result-label hit-label">🏆 HIT</p>
            <p class="confidence">Confidence: {proba*100:.1f}% probability of box office success</p>
        </div>
        """, unsafe_allow_html=True)
    else:
        st.markdown(f"""
        <div class="result-box flop-box">
            <p class="result-label flop-label">💸 FLOP</p>
            <p class="confidence">Confidence: {(1-proba)*100:.1f}% probability of underperforming</p>
        </div>
        """, unsafe_allow_html=True)

    # ── Metrics row ───────────────────────────────────────────
    st.markdown('<p class="section-title">📊 Input Summary</p>', unsafe_allow_html=True)
    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Budget",      f"${budget_m}M")
    m2.metric("Runtime",     f"{runtime} min")
    m3.metric("Hit prob.",   f"{proba*100:.1f}%")
    m4.metric("Buzz score",  str(popularity))

    # ── Insight cards ─────────────────────────────────────────
    st.markdown('<p class="section-title">💡 Key Drivers</p>', unsafe_allow_html=True)

    insights = []

    if dir_hit_rate >= 0.7:
        insights.append("✅ Strong director track record — the #1 predictor of success in this model.")
    elif dir_hit_rate <= 0.3:
        insights.append("⚠️ Director has a weak track record — the biggest risk factor for this film.")

    if budget_m > 150:
        insights.append(f"⚠️ High budget (${budget_m}M) raises the bar — needs blockbuster revenue to recoup.")
    elif budget_m < 20:
        insights.append(f"✅ Low budget (${budget_m}M) lowers the hit threshold — easier ROI to achieve.")

    if "Summer" in season or "Holiday" in season:
        insights.append("✅ Prime release window — summer and holiday slots historically outperform.")
    else:
        insights.append("⚠️ Off-peak release window — harder to drive footfall without competition buffer.")

    if primary_genre == "Horror" and budget_m < 30:
        insights.append("✅ Low-budget Horror is the single most reliable hit formula in the dataset.")

    if primary_genre == "Drama":
        insights.append("⚠️ Drama genre has the lowest hit rate in the dataset — tough box office terrain.")

    if franchise_flag:
        insights.append("✅ Franchise/sequel — built-in audience reduces marketing risk.")

    if big_studio:
        insights.append("✅ Major studio backing — better distribution, marketing muscle, and screen count.")

    for insight in insights:
        st.markdown(f'<div class="insight-card">{insight}</div>',
                    unsafe_allow_html=True)

    # ── Model info footer ─────────────────────────────────────
    st.markdown("---")
    st.caption(
        "Model: XGBoost classifier trained on TMDB 5000 Movies dataset. "
        "Test set ROC-AUC: 0.937. "
        "Prediction uses only pre-release features — no audience scores or revenue data."
    )
